name: high_q_paginated_drop_down
description: Package handles the pagination and search in DropDown .
version: 2.1.4
homepage: https://github.com/azabcodes/high_q_paginated_drop_down

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter
  async: ^2.13.0

dev_dependencies:
  recase: ^4.1.0
  flutter_test:
    sdk: flutter
  version: ^2.0.0
  flutter_lints: ^5.0.0
